appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gXI0T7pOizL3aUL4UwHn9KEDbF6KlV+MflqZPJyLX42a3gA0TMu84eUbuecBdJLYBogzBMpM3zETDA/q0UnNJa2jFm0DUQztjQ5y6ZeMNDXokhudd6U1ZQGonpHc4ToPjStgsXQHOYWMThaByUU4oAeP9q7VgdWm/2PmcH1KpV3R3qHlMUFlGg3/5L2kxwOSTuTwL0712C3v/sunGXLsneK1/wMh3sFe0BNG8Mcr2/LgrSTfTujeC4OASLE+uzOvEEBS4FOgEhwrIQMX8/tBDDSbyOGnHKjaJlpWgiEQ8dEVl9LIhDyvynnprluY1fKDMYvrBhoNv0GiF2Fqx2CEzJXddy+9pKPenSzmuQxVOFemvbD9i0gWu4AOrRlwH531uiw82kUQ23Ufkzsgv0SIgC7+F3ITEnh2vCj+OG4xsq5vIVgrPxwRCkA3T1fBatmTnWCTgMhpMdlNG8YNCc+pUfefcZ4Hrs2/ChjUe9sJEApC1cG0eZT5iuMJATMM2CjiVnK69+4HCM1oQAe0pEtdcPPSrIbI9jGH15zRMgKFWk5AqUz8OOEcMyQ7Rug3aeX2XrJbV5SwetDZf/JnAdMuo7LRceDw1QAHoYuzZ1ZgxzT3fxY/x4KwNhWqbUFddkNwUhu/z8oyFbrSLw1uT797xRXDNxIWK8LA9VAystzJ7/A=}
